all:
	configFile=config1.py blender --background --python blendCreateSnapshot.py
	configFile=config2.py blender --background --python blendCreateSnapshot.py
	configFile=config3.py blender --background --python blendCreateSnapshot.py
